### ISSUE TITLE
[Migrate] React to Next.js (TypeScript) with Tailwind CSS

### ISSUE THREAD

**Issue by abhijeetnishal** [abhijeetnishal/Password-Shield#51]
## Description:
The goal of this issue is to migrate the existing application **client (frontend)** from React to Next.js (with **TypeScript**), utilizing the latest version of Next.js and its App Router. Additionally, the current CSS implementation will be replaced with **Tailwind CSS**.

## Current State:
The current application **client (frontend)** is built using React, with a custom CSS implementation. While this has served the project well, we want to take advantage of the benefits offered by Next.js, such as server-side rendering, improved performance, and a more robust routing system.

## Task Breakdown:
To complete this issue, the following tasks need to be accomplished:
- [ ] Update the project structure to conform to Next.js conventions.
- [ ] Migrate React components to Next.js (with **TypeScript**) pages and components.
- [ ] Implement the Next.js App Router to handle routing.
- [ ] Replace the current CSS implementation with **Tailwind CSS**.
- [ ] Test the application thoroughly to ensure it functions as expected.

## Estimated Time: 
This issue is estimated to take around 4-5 days to complete, depending on the contributor's experience with Next.js and Tailwind CSS.

**Comment by abhijeetnishal** [comment]
This issue is important and high priority that's why i have labeled it level3.
So only take this issue if you have experience with both react and next.js and tailwind because it should be done in defined time so that i can review and merge as there are lot of issue that are dependent on this.

**Comment by HARISH-1222** [comment]
Hay @abhijeetnishal 👋

I worked in NextJs and tailwind

I like to contribute to this under the GSSOC...

**Comment by danmolloy** [comment]
Hi @abhijeetnishal,
I would be happy to take this on if @HARISH-1222 is unavailable. Dan

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, i am assigning this issue to you by seeing your work experience on Next.js and typescript. Try to finish this issue in the given time because many PR are there that's need to be updated.

Hey @HARISH-1222, try to work on other issues. Good luck.

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, how's the migration work going on?

**Comment by danmolloy** [comment]
Hi @abhijeetnishal, it's coming along well and I should be able to do a PR today

**Comment by abhijeetnishal** [comment]
> Hi @abhijeetnishal, it's coming along well and I should be able to do a PR today

Great, if you need any help let me know.

**Comment by danmolloy** [comment]
Hi @abhijeetnishal, I'm sorry but I've been a little snowed in with work and I won't be finished till tomorrow. 

So far I've created a new client dir built with nextjs, migrated all files to typescript and utilised the app router with features such as server components, next/link and next/image components. 

I've still some migrating to do with Tailwind, need to do a little more typing with TypeScript and currently there aren't enough tests that I'm confident it's all running smoothly.

I've some time tomorrow and should be able to get it all done, I appreciate there are a few issues waiting on my PR.

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, it's fine. You can take some more time to finish this, no worries as it's a level3 issue.

If you want you can create a PR for your current work, I will review. This issue is big it will take more time for me to review and test also.

**Comment by danmolloy** [comment]
Hi @abhijeetnishal, just letting you know I'm completed it all and just writing tests now. Dan

**Comment by abhijeetnishal** [comment]
> Hi @abhijeetnishal, just letting you know I'm completed it all and just writing tests now. Dan

Great @danmolloy
